#include "arene/base/testing/prng_xoshiro.hpp"

#include <gmock/gmock.h>  // IWYU pragma: keep
#include <gtest/gtest.h>  // IWYU pragma: keep

#include "arene/base/array/array.hpp"
#include "arene/base/math/power_of_2.hpp"
#include "arene/base/stdlib_choice/cstddef.hpp"
#include "arene/base/testing/gtest.hpp"

namespace {

using arene::base::testing::prng_xoshiro;

constexpr arene::base::array<prng_xoshiro::seed_type, 5U> seeds{0U, 1U, 42U, 12345U, 0xFFAAEEBBDDCCU};

/// @test default constructor produces deterministic output
CONSTEXPR_TEST(PrngXoshiro, DefaultConstructorIsDeterministic) {
  auto prng_a = prng_xoshiro{};
  auto prng_b = prng_xoshiro{};

  CONSTEXPR_ASSERT_EQ(prng_a(), prng_b());
  CONSTEXPR_ASSERT_EQ(prng_a(), prng_b());
  CONSTEXPR_ASSERT_EQ(prng_a(), prng_b());
}

/// @test seeded constructor produces deterministic output for the same seed
CONSTEXPR_TEST(PrngXoshiro, SameSeeedIsDeterministic) {
  for (prng_xoshiro::seed_type const seed : seeds) {
    auto prng_a = prng_xoshiro{seed};
    auto prng_b = prng_xoshiro{seed};

    CONSTEXPR_ASSERT_EQ(prng_a(), prng_b());
    CONSTEXPR_ASSERT_EQ(prng_a(), prng_b());
    CONSTEXPR_ASSERT_EQ(prng_a(), prng_b());
  }
}

/// @test seeds 1 and 2 produce different first values
CONSTEXPR_TEST(PrngXoshiro, DifferentSeedsDifferentSequences) {
  auto prng_a = prng_xoshiro{1U};
  auto prng_b = prng_xoshiro{2U};

  CONSTEXPR_ASSERT_FALSE(prng_a() == prng_b());
}

/// @test successive calls produce different values
CONSTEXPR_TEST(PrngXoshiro, SuccessiveCallsDiffer) {
  auto prng = prng_xoshiro{};

  auto const first = prng();
  auto const second = prng();
  auto const third = prng();

  CONSTEXPR_ASSERT_FALSE(first == second);
  CONSTEXPR_ASSERT_FALSE(second == third);
  CONSTEXPR_ASSERT_FALSE(first == third);
}

/// @test matches known output across all platforms
TEST(PrngXoshiro, MatchesKnownOutput) {
  auto prng = prng_xoshiro{};

  // these values were generated on my local dev machine (arm64-darwin)
  constexpr auto expected = arene::base::array<prng_xoshiro::result_type, 10>{
      5987356902031041503ULL,
      7051070477665621255ULL,
      6633766593972829180ULL,
      211316841551650330ULL,
      9136120204379184874ULL,
      379361710973160858ULL,
      15813423377499357806ULL,
      15596884590815070553ULL,
      5439680534584881407ULL,
      1369371744833522710ULL
  };

  auto actual = arene::base::array<prng_xoshiro::result_type, 10>{};
  for (auto& value : actual) {
    value = prng();
  }

  EXPECT_THAT(actual, testing::ElementsAreArray(expected));
}

/// @test The values generated by the xoshiro generator cover all 64 bits of the result type
CONSTEXPR_TEST(PrngXoshiro, WholeRangeCovered) {
  for (prng_xoshiro::seed_type const seed : seeds) {
    prng_xoshiro prng{seed};
    prng_xoshiro::result_type covered_bits{};

    // The probability of a given bit to be covered after N iterations is 1 - (1/2)^N
    // The probability P of *all* B bits to be covered after N iterations is (1 - (1/2)^N) ^ B
    // (1/2)^N = 1 - P^(1/B) so 2^N = 1 / (1 - P^(1/B)) or N = -log2(1 - P^(1/B))
    // Even for 64 bits, P > 0.99 gives N below 10.
    constexpr std::size_t number_of_iterations{10};
    for (std::size_t i{}; i < number_of_iterations; ++i) {
      covered_bits |= prng();
    }

    CONSTEXPR_ASSERT_EQ(covered_bits, ~prng_xoshiro::result_type{});
  }
}

// This test is not CONSTEXPR because it exceeds the compiler's constexpr iteration limit.
/// @test The values generated by the xoshiro generator are uniformly distributed over the range of its result type
TEST(PrngXoshiro, DistributionIsUniform) {
  using result_type = prng_xoshiro::result_type;

  // The range of the result type is 2^64, divided into 2^6, so each bin is 2^58 bits wide.
  constexpr std::size_t bin_count{arene::base::power_of_2(6U)};  // 128
  constexpr result_type bin_size{arene::base::power_of_2(58U)};

  for (prng_xoshiro::seed_type const seed : seeds) {
    arene::base::array<std::size_t, bin_count> histogram{};
    prng_xoshiro prng{seed};

    constexpr std::size_t number_of_iterations{arene::base::power_of_2(20U)};  // about 1,000,000
    for (std::size_t i{}; i < number_of_iterations; ++i) {
      result_type const generated_value = prng();
      auto const bin_idx = static_cast<std::size_t>(generated_value / bin_size);
      ++histogram[bin_idx];
    }

    // After N iterations, the expected number of samples in each bin is N/bin_count with a standard deviation of
    // sqrt(N/bin_count). There is a 99.994% chance for each bin to be within 4 standard deviations of the expectation,
    // giving a 99.2% chance for all 128 bins to be within 4 standard deviations.

    for (auto const& bin : histogram) {
      constexpr std::size_t expected_count{number_of_iterations / bin_count};                    // 2^14
      constexpr std::size_t expected_standard_deviation{128U};                                   // sqrt(2^14) == 2^7
      constexpr std::size_t lower_4_sigma{expected_count - (4U * expected_standard_deviation)};  // 2^14 - 2^9
      constexpr std::size_t upper_4_sigma{expected_count + (4U * expected_standard_deviation)};  // 2^14 + 2^9

      ASSERT_GE(bin, lower_4_sigma);
      ASSERT_LE(bin, upper_4_sigma);
    }
  }
}

}  // namespace
