# Copyright 2026, Toyota Motor Corporation
#
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

"""
Defines mappings from individual stdlib components to public stdlib headers
"""
# NOTE This file is autogenerated by the Arene CLI command `update-stdlib-build`
# based on the contents of the C++ source files.
# Direct modifications to this file may be lost.

COMPONENTS = [
    struct(
        name = "accumulate",
        public_header = "numeric",
    ),
    struct(
        name = "add_const",
        public_header = "type_traits",
    ),
    struct(
        name = "add_cv",
        public_header = "type_traits",
    ),
    struct(
        name = "add_lvalue_reference",
        public_header = "type_traits",
    ),
    struct(
        name = "add_pointer",
        public_header = "type_traits",
    ),
    struct(
        name = "add_rvalue_reference",
        public_header = "type_traits",
    ),
    struct(
        name = "add_volatile",
        public_header = "type_traits",
    ),
    struct(
        name = "addressof",
        public_header = "memory",
    ),
    struct(
        name = "adjacent_find",
        public_header = "algorithm",
    ),
    struct(
        name = "allocator",
        public_header = "memory",
    ),
    struct(
        name = "basic_insert_iterator",
        public_header = "iterator",
    ),
    struct(
        name = "basic_iterator",
        public_header = "iterator",
    ),
    struct(
        name = "begin",
        public_header = "iterator",
    ),
    struct(
        name = "char_traits",
        public_header = "string",
    ),
    struct(
        name = "climits",
        public_header = "climits",
    ),
    struct(
        name = "common_type",
        public_header = "type_traits",
    ),
    struct(
        name = "conditional",
        public_header = "type_traits",
    ),
    struct(
        name = "copy_n",
        public_header = "algorithm",
    ),
    struct(
        name = "count_if",
        public_header = "algorithm",
    ),
    struct(
        name = "cstddef",
        public_header = "cstddef",
    ),
    struct(
        name = "cstdint",
        public_header = "cstdint",
    ),
    struct(
        name = "decay",
        public_header = "type_traits",
    ),
    struct(
        name = "declval",
        public_header = "utility",
    ),
    struct(
        name = "divides",
        public_header = "functional",
    ),
    struct(
        name = "duration",
        public_header = "chrono",
    ),
    struct(
        name = "enable_if",
        public_header = "type_traits",
    ),
    struct(
        name = "end",
        public_header = "iterator",
    ),
    struct(
        name = "equal_to",
        public_header = "functional",
    ),
    struct(
        name = "exchange",
        public_header = "utility",
    ),
    struct(
        name = "extent",
        public_header = "type_traits",
    ),
    struct(
        name = "find_if_not",
        public_header = "algorithm",
    ),
    struct(
        name = "forward",
        public_header = "utility",
    ),
    struct(
        name = "forward_as_tuple",
        public_header = "tuple",
    ),
    struct(
        name = "greater",
        public_header = "functional",
    ),
    struct(
        name = "greater_equal",
        public_header = "functional",
    ),
    struct(
        name = "hash",
        public_header = "functional",
    ),
    struct(
        name = "ignore",
        public_header = "tuple",
    ),
    struct(
        name = "initializer_list",
        public_header = "initializer_list",
    ),
    struct(
        name = "inner_product",
        public_header = "numeric",
    ),
    struct(
        name = "integer_sequence",
        public_header = "utility",
    ),
    struct(
        name = "integral_constant",
        public_header = "type_traits",
    ),
    struct(
        name = "internal_disable_constexpr_in_cpp14",
        public_header = None,
    ),
    struct(
        name = "internal_named_requirements",
        public_header = None,
    ),
    struct(
        name = "internal_partition_point",
        public_header = None,
    ),
    struct(
        name = "internal_relative_find",
        public_header = None,
    ),
    struct(
        name = "iota",
        public_header = "numeric",
    ),
    struct(
        name = "is_abstract",
        public_header = "type_traits",
    ),
    struct(
        name = "is_arithmetic",
        public_header = "type_traits",
    ),
    struct(
        name = "is_array",
        public_header = "type_traits",
    ),
    struct(
        name = "is_assignable",
        public_header = "type_traits",
    ),
    struct(
        name = "is_base_of",
        public_header = "type_traits",
    ),
    struct(
        name = "is_class",
        public_header = "type_traits",
    ),
    struct(
        name = "is_const",
        public_header = "type_traits",
    ),
    struct(
        name = "is_constructible",
        public_header = "type_traits",
    ),
    struct(
        name = "is_convertible",
        public_header = "type_traits",
    ),
    struct(
        name = "is_copy_assignable",
        public_header = "type_traits",
    ),
    struct(
        name = "is_copy_constructible",
        public_header = "type_traits",
    ),
    struct(
        name = "is_default_constructible",
        public_header = "type_traits",
    ),
    struct(
        name = "is_destructible",
        public_header = "type_traits",
    ),
    struct(
        name = "is_empty",
        public_header = "type_traits",
    ),
    struct(
        name = "is_enum",
        public_header = "type_traits",
    ),
    struct(
        name = "is_final",
        public_header = "type_traits",
    ),
    struct(
        name = "is_floating_point",
        public_header = "type_traits",
    ),
    struct(
        name = "is_function",
        public_header = "type_traits",
    ),
    struct(
        name = "is_fundamental",
        public_header = "type_traits",
    ),
    struct(
        name = "is_integral",
        public_header = "type_traits",
    ),
    struct(
        name = "is_lvalue_reference",
        public_header = "type_traits",
    ),
    struct(
        name = "is_member_function_pointer",
        public_header = "type_traits",
    ),
    struct(
        name = "is_member_object_pointer",
        public_header = "type_traits",
    ),
    struct(
        name = "is_member_pointer",
        public_header = "type_traits",
    ),
    struct(
        name = "is_move_assignable",
        public_header = "type_traits",
    ),
    struct(
        name = "is_move_constructible",
        public_header = "type_traits",
    ),
    struct(
        name = "is_object",
        public_header = "type_traits",
    ),
    struct(
        name = "is_pointer",
        public_header = "type_traits",
    ),
    struct(
        name = "is_reference",
        public_header = "type_traits",
    ),
    struct(
        name = "is_referenceable",
        public_header = "type_traits",
    ),
    struct(
        name = "is_rvalue_reference",
        public_header = "type_traits",
    ),
    struct(
        name = "is_same",
        public_header = "type_traits",
    ),
    struct(
        name = "is_signed",
        public_header = "type_traits",
    ),
    struct(
        name = "is_sorted",
        public_header = "algorithm",
    ),
    struct(
        name = "is_trivially_copyable",
        public_header = "type_traits",
    ),
    struct(
        name = "is_unsigned",
        public_header = "type_traits",
    ),
    struct(
        name = "is_void",
        public_header = "type_traits",
    ),
    struct(
        name = "is_volatile",
        public_header = "type_traits",
    ),
    struct(
        name = "iter_swap",
        public_header = "utility",
    ),
    struct(
        name = "iterator_concepts",
        public_header = None,
    ),
    struct(
        name = "iterator_tags",
        public_header = "iterator",
    ),
    struct(
        name = "iterator_traits",
        public_header = "iterator",
    ),
    struct(
        name = "less",
        public_header = "functional",
    ),
    struct(
        name = "less_equal",
        public_header = "functional",
    ),
    struct(
        name = "logical_and",
        public_header = "functional",
    ),
    struct(
        name = "logical_or",
        public_header = "functional",
    ),
    struct(
        name = "lower_bound",
        public_header = "algorithm",
    ),
    struct(
        name = "make_signed",
        public_header = "type_traits",
    ),
    struct(
        name = "make_tuple",
        public_header = "tuple",
    ),
    struct(
        name = "make_unsigned",
        public_header = "type_traits",
    ),
    struct(
        name = "max",
        public_header = "algorithm",
    ),
    struct(
        name = "max_element",
        public_header = "algorithm",
    ),
    struct(
        name = "max_initializer_list_overload",
        public_header = "algorithm",
    ),
    struct(
        name = "max_value_overload",
        public_header = "algorithm",
    ),
    struct(
        name = "memcpy",
        public_header = "cstring",
    ),
    struct(
        name = "min",
        public_header = "algorithm",
    ),
    struct(
        name = "min_element",
        public_header = "algorithm",
    ),
    struct(
        name = "min_initializer_list_overload",
        public_header = "algorithm",
    ),
    struct(
        name = "min_value_overload",
        public_header = "algorithm",
    ),
    struct(
        name = "minmax_element",
        public_header = "algorithm",
    ),
    struct(
        name = "minus",
        public_header = "functional",
    ),
    struct(
        name = "modulus",
        public_header = "functional",
    ),
    struct(
        name = "move",
        public_header = "utility",
    ),
    struct(
        name = "move_algorithm",
        public_header = "algorithm",
    ),
    struct(
        name = "move_iterator",
        public_header = "iterator",
    ),
    struct(
        name = "multiplies",
        public_header = "functional",
    ),
    struct(
        name = "negate",
        public_header = "functional",
    ),
    struct(
        name = "new",
        public_header = "new",
    ),
    struct(
        name = "none_of",
        public_header = "algorithm",
    ),
    struct(
        name = "not_equal_to",
        public_header = "functional",
    ),
    struct(
        name = "nothrow_t",
        public_header = "new",
    ),
    struct(
        name = "numeric_limits",
        public_header = "limits",
    ),
    struct(
        name = "pair",
        public_header = "utility",
    ),
    struct(
        name = "partial_sort_copy",
        public_header = "algorithm",
    ),
    struct(
        name = "plus",
        public_header = "functional",
    ),
    struct(
        name = "pointer_traits",
        public_header = "memory",
    ),
    struct(
        name = "rank",
        public_header = "type_traits",
    ),
    struct(
        name = "ratio",
        public_header = "ratio",
    ),
    struct(
        name = "reference_wrapper",
        public_header = "functional",
    ),
    struct(
        name = "reference_wrapper_fwd",
        public_header = "functional",
    ),
    struct(
        name = "remove_all_extents",
        public_header = "type_traits",
    ),
    struct(
        name = "remove_const",
        public_header = "type_traits",
    ),
    struct(
        name = "remove_cv",
        public_header = "type_traits",
    ),
    struct(
        name = "remove_extent",
        public_header = "type_traits",
    ),
    struct(
        name = "remove_if",
        public_header = "algorithm",
    ),
    struct(
        name = "remove_pointer",
        public_header = "type_traits",
    ),
    struct(
        name = "remove_reference",
        public_header = "type_traits",
    ),
    struct(
        name = "remove_volatile",
        public_header = "type_traits",
    ),
    struct(
        name = "reverse",
        public_header = "algorithm",
    ),
    struct(
        name = "sort",
        public_header = "algorithm",
    ),
    struct(
        name = "stable_sort",
        public_header = "algorithm",
    ),
    struct(
        name = "stdexcept",
        public_header = "stdexcept",
    ),
    struct(
        name = "string",
        public_header = "string",
    ),
    struct(
        name = "swap",
        public_header = "utility",
    ),
    struct(
        name = "time_point",
        public_header = "chrono",
    ),
    struct(
        name = "tuple",
        public_header = "tuple",
    ),
    struct(
        name = "tuple_cat",
        public_header = "tuple",
    ),
    struct(
        name = "tuple_element",
        public_header = "tuple",
    ),
    struct(
        name = "tuple_fwd",
        public_header = "tuple",
    ),
    struct(
        name = "tuple_size",
        public_header = "tuple",
    ),
    struct(
        name = "underlying_type",
        public_header = "type_traits",
    ),
    struct(
        name = "unique",
        public_header = "algorithm",
    ),
    struct(
        name = "upper_bound",
        public_header = "algorithm",
    ),
    struct(
        name = "void_t",
        public_header = None,
    ),
]
