# Copyright 2026, Toyota Motor Corporation
#
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

"""
Provides rules to generate the stdlib_detail BUILD file and stdlib component
map file.

These are used to provide fine-grained dependencies between //arene/base and
//stdlib.
"""

load("//rules:diff_test.bzl", "diff_test")

visibility("//stdlib/include/stdlib_detail/...")

_STDLIB_DETAIL_DIRECTORY = "stdlib/include/stdlib_detail"
_STDLIB_CHOICE_DIRECTORY = "arene/base/stdlib_choice"

_AUTOGEN_WARNING = """\
# NOTE This file is autogenerated by the Arene CLI command `update-stdlib-build`
# based on the contents of the C++ source files.
# Direct modifications to this file may be lost."""

# The beginning of the BUILD file.
#
# If there are issues with generation, simply revert the build file to *just*
# the prologue and then build the `expected_build_file` target.
#
_BUILD_FILE_PROLOGUE = """\
# Copyright 2026, Toyota Motor Corporation
#
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

{warning}

load("@rules_cc//cc:defs.bzl", "cc_library")
load(
    "//{detail_dir}/private:generate_stdlib_bazel_files.bzl",
    "generate_stdlib_bazel_files",
)
load(
    "//{detail_dir}/private:stdlib_detail_component_library.bzl",
    "stdlib_detail_component_library",
)

filegroup(
    name = "hdrs",
    srcs = glob(["*.hpp"]),
)

generate_stdlib_bazel_files(
    name = "stdlib_bazel_files",
    src = ":hdrs",
)

""".format(
    warning = _AUTOGEN_WARNING,
    detail_dir = _STDLIB_DETAIL_DIRECTORY,
)

# The end of the BUILD file.
#
_BUILD_FILE_EPILOGUE = """\
cc_library(
    name = "stdlib_detail",
    visibility = ["//:__subpackages__"],
    deps = [
{deps}
    ],
)

filegroup(
    name = "package",
    srcs = [
        "BUILD.bazel",
{component_headers}
        "//stdlib/include/stdlib_detail/private:package",
    ],
    visibility = ["//stdlib:__pkg__"],
)
"""

def _double_quote(s):
    """Double quote the given string for use in a BUILD file.

    Args:
      s: string
        The string to quote.

    Returns:
      A quoted version of the string that can be substituted into a BUILD file.
    """
    return "\"{}\"".format(s)

def _indent(s = "", level = 1):
    """Indent the given string.

    Args:
      s: string
        The string to indent.
      level: int
        Indentation level.

    Returns:
      An indented version of the string.
    """
    return (4 * level * " ") + s

def _component_filename(f):
    """Obtain the filename from a file.

    Args:
      f: File
        Header file defining a component.

    Returns:
      A string with the component filename.
    """
    return f.basename

def _component_name(f):
    """Obtain the component name from a file.

    Args:
      f: File
        Header file defining a component.

    Returns:
      A string with the component name.
    """
    return _component_filename(f).removesuffix(".hpp")

def _impl(ctx):
    prologue = ctx.actions.declare_file(ctx.attr.name + ".prologue")
    ctx.actions.write(
        output = prologue,
        content = _BUILD_FILE_PROLOGUE,
    )
    output = [prologue]

    srcs = ctx.attr.src.files.to_list()

    for src in srcs:
        for (script, extension) in [
            (ctx.executable._build_snippet, ".snippet"),
            (ctx.executable._component_mapping, ".mapping"),
        ]:
            f = ctx.actions.declare_file(src.short_path + extension)
            ctx.actions.run_shell(
                inputs = [
                    script,
                    src,
                ],
                outputs = [f],
                command = "{script} {input} > {output}".format(
                    script = script.short_path,
                    input = src.short_path,
                    output = f.path,
                ),
                use_default_shell_env = True,
            )
            output.append(f)

    epilogue = ctx.actions.declare_file(ctx.attr.name + ".epilogue")
    ctx.actions.write(
        output = epilogue,
        content = _BUILD_FILE_EPILOGUE.format(
            deps = "\n".join([
                _indent(_double_quote(":{}".format(_component_name(src))) + ",", 2)
                for src in srcs
            ]),
            component_headers = "\n".join([
                _indent(_double_quote("{}".format(_component_filename(src))) + ",", 2)
                for src in srcs
            ]),
        ),
    )
    output.append(epilogue)

    return [
        DefaultInfo(files = depset(output)),
    ]

_build_file_pieces = rule(
    implementation = _impl,
    attrs = {
        "src": attr.label(
            mandatory = True,
        ),
        "_build_snippet": attr.label(
            allow_single_file = True,
            executable = True,
            default = "//{detail_dir}/private:stdlib_detail_build_snippet.bash".format(
                detail_dir = _STDLIB_DETAIL_DIRECTORY,
            ),
            cfg = "exec",
        ),
        "_component_mapping": attr.label(
            allow_single_file = True,
            executable = True,
            default = "//{detail_dir}/private:stdlib_component_mapping.bash".format(
                detail_dir = _STDLIB_DETAIL_DIRECTORY,
            ),
            cfg = "exec",
        ),
    },
)

def _generated_source_file(**kwargs):
    return struct(
        source_label = "@//{}:{}".format(
            kwargs["pkg"],
            kwargs["file"],
        ),
        source_path = "{}/{}".format(
            kwargs["pkg"],
            kwargs["file"],
        ),
        target = lambda basename: basename + "_" + kwargs["name"],
        output = lambda basename: basename + "." + kwargs["name"],
        **kwargs
    )

_GENERATED_SOURCE_TREE_FILES = [
    _generated_source_file(
        name = "build_file",
        pkg = _STDLIB_DETAIL_DIRECTORY,
        file = "BUILD.bazel",
        generation_commands = [
            "cat $$({pieces} | grep -E '.prologue$$') > $@",
            "cat $$({pieces} | grep -E '.snippet$$') >> $@",
            "cat $$({pieces} | grep -E '.epilogue$$') >> $@",
        ],
    ),
    _generated_source_file(
        name = "components",
        pkg = _STDLIB_CHOICE_DIRECTORY,
        file = "components.bzl",
        generation_commands = [
            "echo '# Copyright 2026, Toyota Motor Corporation' > $@",
            "echo '#' >> $@",
            "echo '# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception' >> $@",
            "echo '' >> $@",
            "echo '\"\"\"' >> $@",
            "echo 'Defines mappings from individual stdlib components to public stdlib headers' >> $@",
            "echo '\"\"\"' >> $@",
            "echo '{warning}' >> $@".format(warning = _AUTOGEN_WARNING),
            "echo '' >> $@",
            "echo 'COMPONENTS = [' >> $@",
            "cat $$({pieces} | grep -E '.mapping$$') | sed 's/^/    /' >> $@",
            "echo ']' >> $@",
        ],
    ),
]

def generate_stdlib_bazel_files(*, name = None, src = None):
    """
    Generate Bazel files from the contents of the stdlib_detail directory.

    Args:
      name: string
        Name for this target.
      src: label
        Filegroup target containing all headers in the stdlib_detail directory.

    This macro generates the following files:
      * stdlib/include/stdlib_detail/BUILD.bazel
      * arene/base/stdlib_choice/components.bzl

    As these files cannot be generated as part of the Bazel analysis phase
    (they exist in the source tree and are used to build the action graph),
    this macro does the following:
      * defines rules to build the *expected* files
      * defines a test for each *actual* source file vs the expected contents
      * defines an executable rule to update files in the source tree
    """
    _build_file_pieces(
        name = name + ".pieces",
        src = src,
    )

    for f in _GENERATED_SOURCE_TREE_FILES:
        native.genrule(
            name = f.target(name) + "_raw",
            srcs = [name + ".pieces"],
            outs = [f.output(name) + ".raw"],
            cmd = "; ".join(f.generation_commands).format(
                pieces = "echo '$(locations :{})' | tr ' ' '\n' ".format(name + ".pieces"),
            ),
        )

        native.genrule(
            name = f.target(name),
            srcs = [f.target(name) + "_raw"],
            outs = [f.output(name)],
            cmd = "cat $< | {buildifier} {args} > $@".format(
                buildifier = "$(location @buildifier_prebuilt//:buildifier)",
                args = " ".join([
                    "-type " + ("build" if f.file == "BUILD.bazel" else "bzl"),
                ]),
            ),
            tools = ["@buildifier_prebuilt//:buildifier"],
        )

        diff_test(
            name = f.target(name) + "_test",
            file1 = f.target(name),
            file2 = f.source_label,
            failure_message = """\
\n\n'{actual}' is not up to date with the contents of the '{detail_dir}' directory.

Please update the vendored file with:

  bazelisk run //{detail_dir}:{update_target}
            """.format(
                actual = f.source_path,
                detail_dir = _STDLIB_DETAIL_DIRECTORY,
                update_target = name + ".update",
            ),
        )

    native.genrule(
        name = name + ".update",
        srcs = [
            f.target(name)
            for f in _GENERATED_SOURCE_TREE_FILES
        ],
        outs = [name + ".update.bash"],
        cmd = "echo '{copy_files}' > $@".format(
            copy_files = "; ".join([
                "cp $(location :{src}) $$BUILD_WORKSPACE_DIRECTORY/{dest}".format(
                    src = f.target(name),
                    dest = f.source_path,
                )
                for f in _GENERATED_SOURCE_TREE_FILES
            ]),
        ),
        executable = True,
        tags = [
            "local",
            "manual",
        ],
    )
