' Copyright 2026, Toyota Motor Corporation
'
' SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

  '' use dark colors from doxygen-awesome

  scale 1.5

  skinparam {
    shadowing false
    responseMessageBelowArrow true
    BackgroundColor #ffffff
    DefaultFontColor #2f4153
    ArrowColor #CC99CD
    NoteBorderColor #f1b602
    NoteBackgroundColor #f1b602
    NoteFontColor #3b2e04
    SequenceLifeLineBorderColor #86a9c4
    SequenceLifeLineBackgroundColor #70b1e9
    SequenceActorBorderColor #86a9c4
    SequenceActorBackgroundColor #70b1e9
    SequenceBoxBorderColor #86a9c4
    SequenceBoxBackgroundColor #70b1e9
    SequenceDividerBorderColor #86a9c4
    SequenceDividerBackgroundColor #38393b
    SequenceGroupBorderColor #86a9c4
    SequenceGroupBackgroundColor #70b1e9
    ActivityBorderColor #86a9c4
    ActivityBackgroundColor #70b1e9
    ActivityBarColor #70b1e9
    StateBorderColor #86a9c4
    StateBackgroundColor #2a2c2f
    StateStartColor #70b1e9
    StateEndColor #70b1e9
    ActorBorderColor #86a9c4
    ActorBackgroundColor #70b1e9
    AgentBorderColor #86a9c4
    AgentBackgroundColor #70b1e9
    EntityBorderColor #86a9c4
    EntityBackgroundColor #70b1e9
    ElementBorderColor #86a9c4
    ElementBackgroundColor #70b1e9
    CardBorderColor #86a9c4
    CardBackgroundColor #70b1e9
    ClassBorderColor #86a9c4
    ClassBackgroundColor #70b1e9
    FileBorderColor #86a9c4
    FileBackgroundColor #70b1e9
    FolderBorderColor #86a9c4
    FolderBackgroundColor #70b1e9
    LegendBorderColor #86a9c4
    LegendBackgroundColor #70b1e9
    LexicalBorderColor #86a9c4
    LexicalBackgroundColor #70b1e9
    NodeBorderColor #86a9c4
    NodeBackgroundColor #70b1e9
    NoteBorderColor #3b2e04
    NoteBackgroundColor #f1b602
    QueueBorderColor #86a9c4
    QueueBackgroundColor #70b1e9
    DatabaseBorderColor #86a9c4
    DatabaseBackgroundColor #70b1e9
    CollectionsBorderColor #86a9c4
    CollectionsBackgroundColor #70b1e9
    ObjectBorderColor #86a9c4
    ObjectBackgroundColor #70b1e9
    RectangleBorderColor #86a9c4
    RectangleBackgroundColor #70b1e9
    StorageBorderColor #86a9c4
    StorageBackgroundColor #70b1e9
  }
