# Copyright 2026, Toyota Motor Corporation
#
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

---
name: Code coverage
run-name: Generating code coverage results
on:
  push:
    branches:
      - main
jobs:
  ubuntu-default-compilers:
    runs-on: ubuntu-24.04
    steps:
      - name: Check out repo
        uses: actions/checkout@v6
      - name: Install libc++
        run: |
          sudo apt update
          sudo apt install -y libc++-dev libc++abi-dev
      - name: >
          Build and test //arene/base/... and //stdlib/... with default clang
          and libc++
        run: |
          bazelisk \
            --bazelrc=.github/ci.bazelrc \
            coverage \
            --keep_going \
            --config=local_toolchain \
            --action_env=CC=clang \
            --copt=-stdlib=libc++ \
            --linkopt=-lc++ \
            -- \
            //:everything //arene/base/... //stdlib/...

      - name: Generate code coverage results
        run: bazel coverage --combined_report=lcov //...

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: woven-by-toyota/arene-base
