# Copyright 2026, Toyota Motor Corporation
#
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

# Simple workflow for deploying static content to GitHub Pages
---
name: Deploy Doxygen Documentation

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between
# the run in-progress and latest queued.  However, do NOT cancel
# in-progress runs as we want to allow these production deployments to
# complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Doxygen
        # yamllint disable rule:line-length
        run: |
          sudo apt-get update && sudo apt-get install -y wget graphviz
          wget https://github.com/doxygen/doxygen/releases/download/Release_1_13_2/doxygen-1.13.2.linux.bin.tar.gz
          tar xf doxygen-1.13.2.linux.bin.tar.gz
          cd doxygen-1.13.2
          sudo make install
        # yamllint enable rule:line-length
      - name: Generate Documentation
        run: |
          doxygen ./docs/doxygen_config
          touch .nojekyll
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload entire repository
          path: "./docs/output/html"
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
