// Copyright 2026, Toyota Motor Corporation
//
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

#ifndef INCLUDE_GUARD_ARENE_BASE_ARENE_BASE_TESTING_GTEST_WITH_MINITEST_CONDITIONAL_TESTS_HPP_
#define INCLUDE_GUARD_ARENE_BASE_ARENE_BASE_TESTING_GTEST_WITH_MINITEST_CONDITIONAL_TESTS_HPP_

// IWYU pragma: private
// IWYU pragma: friend "arene/base/testing/gtest/.*"

#endif  // INCLUDE_GUARD_ARENE_BASE_ARENE_BASE_TESTING_GTEST_WITH_MINITEST_CONDITIONAL_TESTS_HPP_
